server:
  servlet:
    context-path: /
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: b-extend
  mvc:
    static-path-pattern: /**
    path-match:
      matching-strategy: ant_path_matcher
  resource:
    static-locations: classpath:/static/,classpath:/public/
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      hikari:
        validation-timeout: 3000
        min-idle: 10
        max-lifetime: 200000
        max-pool-size: 200
        idle-timeout: 60000
        connection-timeout: 60000
        initialization-fail-timeout: 1000
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/db_userlog_test?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
jeecg:
  path:
    upload: /opt/bsaas_core/upload
swagger:
  enable: true

logging:
  config: classpath:log4j2-dev.xml
